# Generated by Django 4.2.3 on 2024-01-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('comp_vertical', models.CharField(max_length=255)),
                ('job_skills', models.JSONField(blank=True, null=True)),
                ('comp_industry', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
            ],
        ),
    ]
